### ISSUE TITLE
Errors in FGT controllers

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#37] opened 2021-10-14 10:33 UTC
Some new Errors began showing up in some FGT webapp controllers that were NOT there on during the release.

The 3 most probable options are:
 - webcardinal weird update that broke something;
 - Simultaneous use of webapps led to inconsistencies that are not being handled by the controller;
 - our (most probably Vitor's) updates in the services/managers during tests (this is not a blame)

Please debug these controllers and:
1 - Find the source of the errors;
2 - Discuss with me (Tiago) how to solve them

**Comment by pccosta-pdm** [comment] 2021-11-02 14:21
errors have already been solved with parallel commits or, was because of installation issues.

p.s.: there are some errors caused by partners algorithms, already reported. However, for now, I will close this issue.

**Closed** 2021-11-05 16:24 UTC
Labels: bug
